SET(CPM_DOWNLOAD_VERSION 0.37.0)

IF(CPM_SOURCE_CACHE)
    SET(CPM_DOWNLOAD_LOCATION "${CPM_SOURCE_CACHE}/cpm/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
ELSEIF(DEFINED ENV{CPM_SOURCE_CACHE})
    SET(CPM_DOWNLOAD_LOCATION "$ENV{CPM_SOURCE_CACHE}/cpm/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
ELSE()
    SET(CPM_DOWNLOAD_LOCATION "${CMAKE_BINARY_DIR}/cmake/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
ENDIF()

# Expand relative path. This is important if the provided path contains a tilde (~)
GET_FILENAME_COMPONENT(CPM_DOWNLOAD_LOCATION ${CPM_DOWNLOAD_LOCATION} ABSOLUTE)

FUNCTION(download_cpm)
    MESSAGE(STATUS "Downloading CPM.cmake to ${CPM_DOWNLOAD_LOCATION}")
    FILE(DOWNLOAD https://github.com/cpm-cmake/CPM.cmake/releases/download/v${CPM_DOWNLOAD_VERSION}/CPM.cmake
         ${CPM_DOWNLOAD_LOCATION})
ENDFUNCTION()

IF(NOT (EXISTS ${CPM_DOWNLOAD_LOCATION}))
    DOWNLOAD_CPM()
ELSE()
    # resume download if it previously failed
    FILE(READ ${CPM_DOWNLOAD_LOCATION} check)
    IF("${check}" STREQUAL "")
        DOWNLOAD_CPM()
    ENDIF()
ENDIF()

INCLUDE(${CPM_DOWNLOAD_LOCATION})
